#!/bin/bash

set -x

BASEDIR=$(dirname "$(realpath "$0")")
PROJECT_ROOT="$BASEDIR/.."

. $PROJECT_ROOT/tests/common

help() {
  cat <<EOF
Usage: $0 -i <impl>
       $0 --impl=<impl>

Options:
  -i, --impl <impl>        Specify the implementation of the env-exporter program.
                           Must be either 'bash' or 'rust'.

Examples:
  $0 -i bash
  $0 --impl=rust

Description:
  The 'impl' option selects which implementation of the env-exporter program to use.
  - 'bash': Uses the Bash-based implementation.
  - 'rust': Uses the Rust-based implementation.

EOF
  exit 1
}


impl=""

while [[ $# -gt 0 ]]; do
  case "$1" in
  -i=* | --impl=*)
    impl="${1#*=}"
    shift
    ;;
  -i | --impl)
    impl="$2"
    shift 2
    ;;
  *)
    help
    ;;
  esac
done

check_impl "$impl"

inject_test_app "$impl"
